export { default as Angular } from "./Angular";
export { default as C } from "./C";
export { default as CSharp } from "./CSharp";
export { default as Css } from './Css'
export { default as Cpp } from "./Cpp";
export { default as Dart } from "./Dart";
export { default as Flutter } from "./Flutter";
export { default as Go } from "./Go";
export { default as Haskell } from './Haskell'
export { default as Html } from './Html'
export { default as Java } from "./Java";
export { default as Javascript } from './Javascript'
export { default as Julia } from './Julia'
export { default as Kafka } from './Kafka'
export { default as Kubernetes } from './Kubernetes'
export { default as Kotlin } from "./Kotlin";
export { default as Python } from "./Python";
export { default as React1 } from "./React";
export { default as Rust } from './Rust'
export { default as Swift } from "./Swift";
export { default as Svelte } from './Svelte'
export { default as Typescript } from './Typescript'
export { default as Vue } from "./Vue";
